server:
  port: 84


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
    sentinel:
      transport:
        dashboard: 192.168.75.130:8080
        port: 8719
        clientIp: 192.168.75.1  #地址问题会导致sentinel 没有监控，Linux 192.168.75.XXX,192.168.75.1本机虚拟网卡地址

service-url:
  nacos-user-service: http://nacos-payment-provider

#对Feign的支持
feign:
  sentinel:
    enabled: true

